version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:22.1.0-browsers # Includes Node.js, Chrome, and Firefox
    working_directory: ~/project

jobs:
  cypress-tests:
    executor: node-executor
    steps:
      - checkout

      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}

      - run:
          name: Install dependencies
          command: npm ci

      - save_cache:
          paths:
            - ~/.npm
          key: npm-cache-{{ checksum "package-lock.json" }}

      - run:
          name: Run Cypress tests in Chrome
          command: npm run test:cci
          when: always

      - run:
          name: Merge Mochawesome reports
          command: |
            mkdir -p cypress/results
            npx mochawesome-merge cypress/results/*.json > cypress/results/merged-reports.json || echo "No reports to merge."

      - run:
          name: Generate HTML report
          command: npx mochawesome-report-generator cypress/results/merged-reports.json --reportDir cypress/results --reportFilename test-report.html

      - store_artifacts:
          path: cypress/results
          destination: mochawesome-report

workflows:
  version: 2
  run-cypress-tests:
    jobs:
      - cypress-tests
