name: Cypress Tests

on:
  push:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run in Chrome
        uses: cypress-io/github-action@v6
        with:
          browsers: chrome
          command: npx cypress run --browser chrome --reporter-options reportDir=cypress/reports

      - name: Merge Mochaawesome reports
        run: npx mochaawesome-merge cypress/reports/*.json > cypress/reports/merged-reports.json

      - name: Generate HTML Reports
        run: npx cypress/reports/merged-reports.json --reportDir cypress/reports -f "test-report.html"

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: Cypress HTML Report
          path: cypress/reports
